### PR TITLE
Restore Satoshi copyright.

### PR DESCRIPTION
**Pull request by shadders**
Restore copyright notice for the original author.

### CODE REVIEW

**Comment by jaggedsoft** [comment]
LGTM 👍

**Comment by dagurval** [comment]
For reference, this partially reverts Satoshi's change here https://github.com/bitcoin-sv/bitcoin-sv/commit/fc73ad644f0b87b91f49b7f6f6b2348f78bdbbf4

**Comment by Danconnolly** [comment]
Done.

**Comment by screeni** [comment]
thank you

**Pull request closed without merging**
